### ISSUE TITLE
Excuse me, how to deploy the public directory cannot be specified?

### ISSUE THREAD

**Issue by wfsdaj** [lightpack/lightpack#86]
I'm using a virtual host. I can't specify the public directory as the root directory. So, I use the following. Htaccess file in the upper public directory, but it doesn't work.

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule  (.*) public/$1 [L]
</IfModule>
```

thanks!

**Comment by pradeep-tiwari** [comment]
Hello, there are a couple of ways to deploy the project in public directory. I can't help you exactly because I don't know what setup you are using but here are few of my recommendations:

**Running on Unix/Linux based setup on ,l**

If you run your PHP apps on ***nix** based system, you can simply run the project through command line. For that, open your terminal and navigate to your public folder and run the web server as show below:

**php -S 127.0.0.1:3000**

You should use an **IP** and **port** that is available for you.

_Please note that this project is not ready for production yet but I expect that in next few weeks (3-4 maybe) the project will be released for version 1._

Also this project has been tested on ***nix** based system. I have no plans to support **Windows** for now.

But still if you are trying to deploy this project on live server, then configure your apache to point to public directory as show:

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName your_domain
    ServerAlias www.your_domain
    DocumentRoot /var/www/your_domain/public
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
**NOTE**: You don't have to deal with **.htaccess** for this. Having proper **vhost** configuration in **Apache** should do the job.
